//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"kubenetlab.net/knl/common"
	corev1 "kubevirt.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connector) DeepCopyInto(out *Connector) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.PortId != nil {
		in, out := &in.PortId, &out.PortId
		*out = new(string)
		**out = **in
	}
	if in.Addr != nil {
		in, out := &in.Addr, &out.Addr
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connector.
func (in *Connector) DeepCopy() *Connector {
	if in == nil {
		return nil
	}
	out := new(Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralPod) DeepCopyInto(out *GeneralPod) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = new(string)
		**out = **in
	}
	if in.Privileged != nil {
		in, out := &in.Privileged, &out.Privileged
		*out = new(bool)
		**out = **in
	}
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralPod.
func (in *GeneralPod) DeepCopy() *GeneralPod {
	if in == nil {
		return nil
	}
	out := new(GeneralPod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralVM) DeepCopyInto(out *GeneralVM) {
	*out = *in
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.PinCPU != nil {
		in, out := &in.PinCPU, &out.PinCPU
		*out = new(bool)
		**out = **in
	}
	if in.HugePage != nil {
		in, out := &in.HugePage, &out.HugePage
		*out = new(bool)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.InitMethod != nil {
		in, out := &in.InitMethod, &out.InitMethod
		*out = new(string)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]corev1.Port)
		if **in != nil {
			in, out := *in, *out
			*out = make([]corev1.Port, len(*in))
			copy(*out, *in)
		}
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralVM.
func (in *GeneralVM) DeepCopy() *GeneralVM {
	if in == nil {
		return nil
	}
	out := new(GeneralVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfig) DeepCopyInto(out *KNLConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfig.
func (in *KNLConfig) DeepCopy() *KNLConfig {
	if in == nil {
		return nil
	}
	out := new(KNLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KNLConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigList) DeepCopyInto(out *KNLConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KNLConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigList.
func (in *KNLConfigList) DeepCopy() *KNLConfigList {
	if in == nil {
		return nil
	}
	out := new(KNLConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KNLConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigSpec) DeepCopyInto(out *KNLConfigSpec) {
	*out = *in
	if in.SFTPSever != nil {
		in, out := &in.SFTPSever, &out.SFTPSever
		*out = new(string)
		**out = **in
	}
	if in.VXLANGrpAddr != nil {
		in, out := &in.VXLANGrpAddr, &out.VXLANGrpAddr
		*out = new(string)
		**out = **in
	}
	if in.VXLANDefaultDev != nil {
		in, out := &in.VXLANDefaultDev, &out.VXLANDefaultDev
		*out = new(string)
		**out = **in
	}
	if in.VxDevMap != nil {
		in, out := &in.VxDevMap, &out.VxDevMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PVCStorageClass != nil {
		in, out := &in.PVCStorageClass, &out.PVCStorageClass
		*out = new(string)
		**out = **in
	}
	if in.SRCPMLoaderImage != nil {
		in, out := &in.SRCPMLoaderImage, &out.SRCPMLoaderImage
		*out = new(string)
		**out = **in
	}
	if in.SRIOMLoaderImage != nil {
		in, out := &in.SRIOMLoaderImage, &out.SRIOMLoaderImage
		*out = new(string)
		**out = **in
	}
	if in.SideCarHookImg != nil {
		in, out := &in.SideCarHookImg, &out.SideCarHookImg
		*out = new(string)
		**out = **in
	}
	if in.DefaultNode != nil {
		in, out := &in.DefaultNode, &out.DefaultNode
		*out = new(OneOfSystem)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigSpec.
func (in *KNLConfigSpec) DeepCopy() *KNLConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KNLConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigStatus) DeepCopyInto(out *KNLConfigStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigStatus.
func (in *KNLConfigStatus) DeepCopy() *KNLConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KNLConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lab) DeepCopyInto(out *Lab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lab.
func (in *Lab) DeepCopy() *Lab {
	if in == nil {
		return nil
	}
	out := new(Lab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Lab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabList) DeepCopyInto(out *LabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Lab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabList.
func (in *LabList) DeepCopy() *LabList {
	if in == nil {
		return nil
	}
	out := new(LabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabSpec) DeepCopyInto(out *LabSpec) {
	*out = *in
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make(map[string]*OneOfSystem, len(*in))
		for key, val := range *in {
			var outVal *OneOfSystem
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(OneOfSystem)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.LinkList != nil {
		in, out := &in.LinkList, &out.LinkList
		*out = make(map[string]*Link, len(*in))
		for key, val := range *in {
			var outVal *Link
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Link)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabSpec.
func (in *LabSpec) DeepCopy() *LabSpec {
	if in == nil {
		return nil
	}
	out := new(LabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabStatus) DeepCopyInto(out *LabStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabStatus.
func (in *LabStatus) DeepCopy() *LabStatus {
	if in == nil {
		return nil
	}
	out := new(LabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GWAddr != nil {
		in, out := &in.GWAddr, &out.GWAddr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MAGC) DeepCopyInto(out *MAGC) {
	*out = *in
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(SRChassis)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MAGC.
func (in *MAGC) DeepCopy() *MAGC {
	if in == nil {
		return nil
	}
	out := new(MAGC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OneOfSystem) DeepCopyInto(out *OneOfSystem) {
	*out = *in
	if in.VSIM != nil {
		in, out := &in.VSIM, &out.VSIM
		*out = new(VSIM)
		(*in).DeepCopyInto(*out)
	}
	if in.VSRI != nil {
		in, out := &in.VSRI, &out.VSRI
		*out = new(VSRI)
		(*in).DeepCopyInto(*out)
	}
	if in.MAGC != nil {
		in, out := &in.MAGC, &out.MAGC
		*out = new(MAGC)
		(*in).DeepCopyInto(*out)
	}
	if in.VM != nil {
		in, out := &in.VM, &out.VM
		*out = new(GeneralVM)
		(*in).DeepCopyInto(*out)
	}
	if in.SRL != nil {
		in, out := &in.SRL, &out.SRL
		*out = new(SRLinux)
		(*in).DeepCopyInto(*out)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(GeneralPod)
		(*in).DeepCopyInto(*out)
	}
	if in.SRSIM != nil {
		in, out := &in.SRSIM, &out.SRSIM
		*out = new(SRSim)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OneOfSystem.
func (in *OneOfSystem) DeepCopy() *OneOfSystem {
	if in == nil {
		return nil
	}
	out := new(OneOfSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRCard) DeepCopyInto(out *SRCard) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.SysInfo != nil {
		in, out := &in.SysInfo, &out.SysInfo
		*out = new(string)
		**out = **in
	}
	if in.MDAs != nil {
		in, out := &in.MDAs, &out.MDAs
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.XIOM != nil {
		in, out := &in.XIOM, &out.XIOM
		*out = make(map[string]XIOM, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ListenPorts != nil {
		in, out := &in.ListenPorts, &out.ListenPorts
		*out = new([]corev1.Port)
		if **in != nil {
			in, out := *in, *out
			*out = make([]corev1.Port, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRCard.
func (in *SRCard) DeepCopy() *SRCard {
	if in == nil {
		return nil
	}
	out := new(SRCard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRChassis) DeepCopyInto(out *SRChassis) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(common.NodeType)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Cards != nil {
		in, out := &in.Cards, &out.Cards
		*out = make(map[string]*SRCard, len(*in))
		for key, val := range *in {
			var outVal *SRCard
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(SRCard)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.SFM != nil {
		in, out := &in.SFM, &out.SFM
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRChassis.
func (in *SRChassis) DeepCopy() *SRChassis {
	if in == nil {
		return nil
	}
	out := new(SRChassis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRLChassis) DeepCopyInto(out *SRLChassis) {
	*out = *in
	out.ChassisConfiguration = in.ChassisConfiguration
	if in.SlotConfig != nil {
		in, out := &in.SlotConfig, &out.SlotConfig
		*out = make(map[int]slotConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRLChassis.
func (in *SRLChassis) DeepCopy() *SRLChassis {
	if in == nil {
		return nil
	}
	out := new(SRLChassis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRLinux) DeepCopyInto(out *SRLinux) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(string)
		**out = **in
	}
	if in.LicSecret != nil {
		in, out := &in.LicSecret, &out.LicSecret
		*out = new(string)
		**out = **in
	}
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRLinux.
func (in *SRLinux) DeepCopy() *SRLinux {
	if in == nil {
		return nil
	}
	out := new(SRLinux)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRSim) DeepCopyInto(out *SRSim) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(SRChassis)
		(*in).DeepCopyInto(*out)
	}
	if in.LicSecret != nil {
		in, out := &in.LicSecret, &out.LicSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRSim.
func (in *SRSim) DeepCopy() *SRSim {
	if in == nil {
		return nil
	}
	out := new(SRSim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRVM) DeepCopyInto(out *SRVM) {
	*out = *in
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(SRChassis)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRVM.
func (in *SRVM) DeepCopy() *SRVM {
	if in == nil {
		return nil
	}
	out := new(SRVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSIM) DeepCopyInto(out *VSIM) {
	*out = *in
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(SRChassis)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSIM.
func (in *VSIM) DeepCopy() *VSIM {
	if in == nil {
		return nil
	}
	out := new(VSIM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VSRI) DeepCopyInto(out *VSRI) {
	*out = *in
	if in.Chassis != nil {
		in, out := &in.Chassis, &out.Chassis
		*out = new(SRChassis)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VSRI.
func (in *VSRI) DeepCopy() *VSRI {
	if in == nil {
		return nil
	}
	out := new(VSRI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XIOM) DeepCopyInto(out *XIOM) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.MDAs != nil {
		in, out := &in.MDAs, &out.MDAs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XIOM.
func (in *XIOM) DeepCopy() *XIOM {
	if in == nil {
		return nil
	}
	out := new(XIOM)
	in.DeepCopyInto(out)
	return out
}
