//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	corev1 "kubevirt.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connector) DeepCopyInto(out *Connector) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.PortId != nil {
		in, out := &in.PortId, &out.PortId
		*out = new(string)
		**out = **in
	}
	if in.Addr != nil {
		in, out := &in.Addr, &out.Addr
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connector.
func (in *Connector) DeepCopy() *Connector {
	if in == nil {
		return nil
	}
	out := new(Connector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfig) DeepCopyInto(out *KNLConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfig.
func (in *KNLConfig) DeepCopy() *KNLConfig {
	if in == nil {
		return nil
	}
	out := new(KNLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KNLConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigList) DeepCopyInto(out *KNLConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KNLConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigList.
func (in *KNLConfigList) DeepCopy() *KNLConfigList {
	if in == nil {
		return nil
	}
	out := new(KNLConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KNLConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigSpec) DeepCopyInto(out *KNLConfigSpec) {
	*out = *in
	if in.SFTPUser != nil {
		in, out := &in.SFTPUser, &out.SFTPUser
		*out = new(string)
		**out = **in
	}
	if in.SFTPPassword != nil {
		in, out := &in.SFTPPassword, &out.SFTPPassword
		*out = new(string)
		**out = **in
	}
	if in.SFTPSever != nil {
		in, out := &in.SFTPSever, &out.SFTPSever
		*out = new(string)
		**out = **in
	}
	if in.VXLANGrpPrefix != nil {
		in, out := &in.VXLANGrpPrefix, &out.VXLANGrpPrefix
		*out = new(string)
		**out = **in
	}
	if in.LinkMtu != nil {
		in, out := &in.LinkMtu, &out.LinkMtu
		*out = new(uint)
		**out = **in
	}
	if in.PVCStorageClass != nil {
		in, out := &in.PVCStorageClass, &out.PVCStorageClass
		*out = new(string)
		**out = **in
	}
	if in.SRCPMLoaderImage != nil {
		in, out := &in.SRCPMLoaderImage, &out.SRCPMLoaderImage
		*out = new(string)
		**out = **in
	}
	if in.SRIOMLoaderImage != nil {
		in, out := &in.SRIOMLoaderImage, &out.SRIOMLoaderImage
		*out = new(string)
		**out = **in
	}
	if in.SideCarHookImg != nil {
		in, out := &in.SideCarHookImg, &out.SideCarHookImg
		*out = new(string)
		**out = **in
	}
	in.DefaultNode.DeepCopyInto(&out.DefaultNode)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigSpec.
func (in *KNLConfigSpec) DeepCopy() *KNLConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KNLConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KNLConfigStatus) DeepCopyInto(out *KNLConfigStatus) {
	*out = *in
	if in.ObservedGeneration != nil {
		in, out := &in.ObservedGeneration, &out.ObservedGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KNLConfigStatus.
func (in *KNLConfigStatus) DeepCopy() *KNLConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KNLConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Lab) DeepCopyInto(out *Lab) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Lab.
func (in *Lab) DeepCopy() *Lab {
	if in == nil {
		return nil
	}
	out := new(Lab)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Lab) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabList) DeepCopyInto(out *LabList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Lab, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabList.
func (in *LabList) DeepCopy() *LabList {
	if in == nil {
		return nil
	}
	out := new(LabList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LabList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabSpec) DeepCopyInto(out *LabSpec) {
	*out = *in
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make(map[string]*OneOfSystem, len(*in))
		for key, val := range *in {
			var outVal *OneOfSystem
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(OneOfSystem)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.LinkList != nil {
		in, out := &in.LinkList, &out.LinkList
		*out = make(map[string]*Link, len(*in))
		for key, val := range *in {
			var outVal *Link
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Link)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabSpec.
func (in *LabSpec) DeepCopy() *LabSpec {
	if in == nil {
		return nil
	}
	out := new(LabSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabStatus) DeepCopyInto(out *LabStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabStatus.
func (in *LabStatus) DeepCopy() *LabStatus {
	if in == nil {
		return nil
	}
	out := new(LabStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]Connector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GWAddr != nil {
		in, out := &in.GWAddr, &out.GWAddr
		*out = new(string)
		**out = **in
	}
	if in.MTU != nil {
		in, out := &in.MTU, &out.MTU
		*out = new(uint16)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OneOfSystem) DeepCopyInto(out *OneOfSystem) {
	*out = *in
	if in.SRVM != nil {
		in, out := &in.SRVM, &out.SRVM
		*out = new(SRVM)
		(*in).DeepCopyInto(*out)
	}
	if in.VMPC != nil {
		in, out := &in.VMPC, &out.VMPC
		*out = new(VMPC)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OneOfSystem.
func (in *OneOfSystem) DeepCopy() *OneOfSystem {
	if in == nil {
		return nil
	}
	out := new(OneOfSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SRVM) DeepCopyInto(out *SRVM) {
	*out = *in
	if in.SRSysinfoStr != nil {
		in, out := &in.SRSysinfoStr, &out.SRSysinfoStr
		*out = new(string)
		**out = **in
	}
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.LicURL != nil {
		in, out := &in.LicURL, &out.LicURL
		*out = new(string)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]corev1.Port)
		if **in != nil {
			in, out := *in, *out
			*out = make([]corev1.Port, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRVM.
func (in *SRVM) DeepCopy() *SRVM {
	if in == nil {
		return nil
	}
	out := new(SRVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMPC) DeepCopyInto(out *VMPC) {
	*out = *in
	if in.ReqMemory != nil {
		in, out := &in.ReqMemory, &out.ReqMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReqCPU != nil {
		in, out := &in.ReqCPU, &out.ReqCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]int32)
		if **in != nil {
			in, out := *in, *out
			*out = make([]int32, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMPC.
func (in *VMPC) DeepCopy() *VMPC {
	if in == nil {
		return nil
	}
	out := new(VMPC)
	in.DeepCopyInto(out)
	return out
}
