# KNL environment — generated by setup-k3s.sh on Mon Jul  6 03:52:21 PM PDT 2026
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export KNL_CNI_BIN_DIR=/var/lib/rancher/k3s/data/cni/
export KNL_MULTUS_CONF_DIR=/var/lib/rancher/k3s/agent/etc/cni/net.d
export KNL_MULTUS_KUBECONFIG=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
export KNL_MULTUS_AUTOCONF_DIR=/var/lib/rancher/k3s/agent/etc/cni/net.d
export KNL_STORAGE_CLASS=local-path
export KNL_REGISTRY=localhost:30500
